config/routes.rb
Flashmeet::Application.routes.draw do
  
  root :to => 'home#index'
  
  resources :users
  resources :categories, :only => [:show, :index]
  resources :meetups

  match 'auth/:provider/callback', to: 'sessions#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'sessions#destroy', as: 'signout'
  match 'meetups/join/:id', to: 'meetups#join', as: 'meetup_join'

end

app/models/category.rb
class Category < ActiveRecord::Base

  def uncapitalized_name
    self.category[0, 1].downcase + self.category[1..-1]
  end
end

app/models/meetup.rb
class Meetup < ActiveRecord::Base
  has_and_belongs_to_many :users
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  def is_attending(meetup)
    meetup.users.include?(self)
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["uid"]
      user.name = auth["info"]["name"]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  def show
    @category = Category.find(params[:id])
    @notice = params[:notice]
    all_meetups = Meetup.where(:category_id => @category.id)
    @meetups_i_am_attending = all_meetups.find_all { |meetup| current_user.is_attending meetup }
    @meetups_i_am_not_attending = all_meetups.find_all { |meetup| !current_user.is_attending meetup }

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @categories = Category.find(:all)

  end
end

app/controllers/meetups_controller.rb
class MeetupsController < ApplicationController

  include MeetupsHelper

  def join
    meetup = Meetup.find(params[:id])
    unless current_user.is_attending meetup
      meetup.users << current_user
      meetup.save!
    end
    respond_to do |format|
      format.html
    end
  end

  def create
    category = Category.find(params[:category_id])
    location = params[:location_name]
    @meetup = Meetup.new
    @meetup.category = category
    @meetup.location = location
    @meetup.users << current_user

    respond_to do |format|
      if @meetup.save
        format.html { redirect_to :controller => "categories", :action=> "show", :id => params[:category_id],  notice: 'Meetup was successfully created! :)' }
      else
        format.html { render action: "new" }
      end
    end
  end

  def new
    category = Category.find(params[:category_id])
    @category_id = params[:category_id]
    @meetup = Meetup.new
    @meetup.category = category
    @suggestions = indications_for get_yelp_category_for(category.category)
    respond_to do |format|
      format.html
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, :notice => "Signed out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # GET /users
  # GET /users.json
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def path_to_login
    Rails.env.production? ? "/auth/twitter/" : "/auth/developer/"
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/meetups_helper.rb
#require 'yelp'

module MeetupsHelper

  require 'rubygems'
  require 'oauth'


  def get_yelp_category_for our_category
    categories = {"eat" => "restaurants"}
    categories[our_category.downcase]
  end

  def indications_for category

    consumer_key = 'OgB1WnTGDFzqI_LF-FlgIA'
    consumer_secret = 'RCFBWNSc-fNiSP8xoy-OAWhoXdY'
    token = '7gZZAMdYe8Ggs6EnfDz5rJXGbkSn4NBG'
    token_secret = 'xG_qA2YxfwX3F1T_R9ZqKg0ZphI'

    #client = Yelp.client.new


    # perform a location-based category search for either ice cream or donut shops in SF
    #request = Yelp::Review::Request::Location.new(
    #    :city => 'New York',
    #    :state => 'NY',
    #    :category => [ category ],
    #    :yws_id => '7wmXg71hx32JtbtmFWsKgw')
    #
    #response = client.search(request)
    #puts "****"
    #puts response


    api_host = 'api.yelp.com'

    consumer = OAuth::Consumer.new(consumer_key, consumer_secret, {:site => "http://#{api_host}"})
    access_token = OAuth::AccessToken.new(consumer, token, token_secret)

    path = "/v2/search?term=#{category}&location=new%20york&limit=3"

    body = access_token.get(path).body
    p body
    as_json = JSON.parse(body)["businesses"]
    locations = []
    as_json.each {|location|
     locations << location["name"]
    }
    p "****"
    p locations
    p "****"
    locations
  end

end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <tr>
    <th>Category</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @categories.each do |category| %>
  <tr>
    <td><%= category.category %></td>
    <td><%= link_to 'Show', category %></td>
    <td><%= link_to 'Edit', edit_category_path(category) %></td>
    <td><%= link_to 'Destroy', category, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<% if @notice %>
<h3><%= @notice %></h3>
<%end %>

<%= render :partial => '/home/logo' %>

<% if @meetups_i_am_not_attending.present? %>
  <ul data-role="listview" data-inset="true" data-theme="c" data-dividertheme="b">
    <li data-role="list-divider" role="heading">Some people are already meeting up to <%= @category.uncapitalized_name %>, join them!</li>
    <% @meetups_i_am_not_attending.each do |meetup| %>
      <li>
        <div class="meetup">
          <p><span class="label">Location:</span> <%= meetup.location %></p>
          <p><span class="label">Created at:</span> <%= meetup.created_at %></p>
          <p><span class="label">Attending:</span></p>
          <% meetup.users.each do |user| %>
            <div class="user-details">
              <% if user.avatar.present? %>
                <div class="avatar"></div>
              <% end %>
              <%= user.name %>
            </div>
          <% end %>
          <%= link_to 'Join them!', meetup_join_path(meetup), 'data-role' => 'button' %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @meetups_i_am_attending.present? %>
  <ul data-role="listview" data-inset="true" data-theme="e" data-dividertheme="a">
    <li data-role="list-divider" role="heading">Meetups I am going to:</li>
    <% @meetups_i_am_attending.each do |meetup| %>
      <li>
        <div class="meetup">
          <p><span class="label">Location:</span> <%= meetup.location %></p>
          <p><span class="label">Created at:</span> <%= meetup.created_at %></p>
          <p><span class="label">Attending:</span></p>
          <% meetup.users.each do |user| %>
            <div class="user-details">
              <% if user.avatar.present? %>
                <div class="avatar"></div>
              <% end %>
              <%= user.name %>
            </div>
          <% end %>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

<div id="create-new-meetup">
  <%= link_to "Create new #{@category.category} meetup!", "/meetups/new?category_id=#{@category.id}", 'data-role' => 'button','data-ajax' => 'false' %>
</div>

app/views/home/_logo.html.erb
<h1 class="logo">FlashMeet</h1>

app/views/home/index.erb
<% if current_user %>
  <%= render :partial => 'logo' %>
  <p class="intro-message">Welcome <%= current_user.name %>!</p>
  <div class="clearfix"></div>
  <ul data-role="listview" data-inset="true" id="categories-list">
    <li data-role="list-divider" role="heading"><h1>What do I want to do today?</li>
    <% @categories.each do |category| %>
      <li><%= link_to category.category, "/categories/#{category.id}" %></li>
    <% end %>
  </ul>
  <script>
    var FM = FM || {};
    FM.location = (function () {
      var self = {};

      function showPosition(position) {
        var anchors = $("#categories-list").find("a");
        var lat = position.coords.latitude;
        var lon = position.coords.longitude;
        $.each(anchors, function (index, value) {
          value = $(value);
          var href = value.attr("href");
          console.log(href);
          var newHref = href + "?lat=" + lat + "&lon=" + lon;
          value.attr("href", newHref);
        });
      }
      function getLocation() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(showPosition);
        }
        else{
          alert("Geolocation is not supported by this browser.");
        }
      }

      self.init = function () {
        getLocation();
      };

      return self;
    })();

    $(function () {
      FM.location.init();
    });
  </script>
<% else %>
  <%= render :partial => 'logo' %>
  <p>Facilitating spontaneity, making new friends!</p>
  <%= link_to "Sign in with Twitter", path_to_login, 'data-role' => 'button', 'data-ajax' => 'false' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashmeet</title>
  <meta name="viewport" content="width=device-width, initial-scale=1"> 
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div data-role="page">
  <div data-role="content">
    <%= yield %>
  </div>
  <div data-role="footer">
    <p>Flashmeet developed @ Hack'n'Jill - NYC, June 2012</p>
  </div>
</div>

</body>
</html>

app/views/meetups/_form.html.erb
<%= form_for(@meetup) do |f| %>
  <% if @meetup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meetup.errors.count, "error") %> prohibited this meetup from being saved:</h2>

      <ul>
      <% @meetup.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <input type="hidden" name="category_id" value="<%=@category_id %>"/>
    <div class="field">
      <select id="location_name" name="location_name">
        <% @suggestions.each do |sugg| %>
        <option value="<%= sugg %>"><%= sugg %> </option>

        <% end %>
      </select>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetups/edit.html.erb
<h1>Editing meetup</h1>

<%= render 'form' %>

<%= link_to 'Show', @meetup %> |
<%= link_to 'Back', meetups_path %>

app/views/meetups/index.html.erb
<h1>Listing meetups</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetups.each do |meetup| %>
  <tr>
    <td><%= link_to 'Show', meetup %></td>
    <td><%= link_to 'Edit', edit_meetup_path(meetup) %></td>
    <td><%= link_to 'Destroy', meetup, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meetup', new_meetup_path %>

app/views/meetups/join.html.erb
Thanks for joining!

app/views/meetups/new.html.erb
<h1>New meetup</h1>

<%= render 'form' %>

<%= link_to 'Back', meetups_path %>

app/views/meetups/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_meetup_path(@meetup) %> |
<%= link_to 'Back', meetups_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br />
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Login</th>
    <th>Name</th>
    <th>Avatar</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.login %></td>
    <td><%= user.name %></td>
    <td><%= user.avatar %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Login:</b>
  <%= @user.login %>
</p>

<p>
  <b>Name:</b>
  <%= @user.name %>
</p>

<p>
  <b>Avatar:</b>
  <%= @user.avatar %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>